export const expositions = 
    {
        "_id": "6a5df2a6fce115360859ed87",
        "title": "Image à Paris",
        "address": "21 Avenue de l'Opéra, 75001 Paris, france",
        "theme": {
            "_id": "6a579213a02baa529ee531de",
            "name": "Nature",
            "description": "Paysages, forêts, montagnes, fleurs et animaux sauvages."
        },
        "description": "Image pour rememorer les anciens vies",
        "maxVisitor": 3,
        "maxExposer": 2,
        "duration": 120,
        "startDate": "2027-01-01T00:00:00.000Z",
        "endDate": "2027-02-02T00:00:00.000Z",
        "createdAt": "2026-07-20T10:04:22.135Z",
        "updatedAt": "2026-07-20T10:04:22.135Z",
        "reservationCount" : 0,
        "__v": 0
    }
